name: PullRequest

on: [pull_request]

jobs:
  buildTest:
    name: Build & Test JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [1.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Decrypt keystore
        run: ./signing/decrypt.sh
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
      - name: Build project
        run: ./gradlew clean assembleDebug -Ponly_x86_64
        env:
          VERSION: ${{ github.ref }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
      - name: cleanup keystore
        run: ./signing/cleanup.sh
      - name: Run tests
        run: ./gradlew test -Ponly_x86_64
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.1
        env:
          VERSION: ${{ github.ref }}
        with:
          cmd: ./gradlew cAT  -Ponly_x86_64 --continue
          api: 28
          tag: default
          abi: x86_64
      - name: Archive Espresso results
        uses: actions/upload-artifact@v2.1.4
        if: ${{ always() }}
        with:
          name: MediaPipe-Espresso-report
          path: ./**/build/reports/androidTests/connected/
      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: MediaPipe-logcat
          path: artifacts/logcat.log
      - name: Archive screenshots
        uses: actions/upload-artifact@v2.1.4
        if: ${{ always() }}
        with:
          name: MediaPipe-Screenshots
          path: screenshots/adb/
      - name: Keep apk
        uses: actions/upload-artifact@v2.1.4
        if: ${{ always() }}
        with:
          name: MediaPipe-apk
          path: ./**/build/outputs/apk/debug/*.apk
          retention-days: 2
      - name: cleanup keystore
        run: ./signing/cleanup.sh
  Check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Decrypt keystore
        run: ./signing/decrypt.sh
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
      - name: Code checks
        run: ./gradlew check
      - name: cleanup keystore
        run: ./signing/cleanup.sh
      - name: Archive Lint report
        uses: actions/upload-artifact@v2.2.2
        if: ${{ always() }}
        with:
          name: MediaPipe-Lint-report
          path: ./**/build/reports/lint-results.html
